### ISSUE TITLE
Sample code gives ChainExpression error

### ISSUE THREAD

**Issue by bitofbreeze** [uwdata/arquero#373]
Running the sample code from the readme for the first time:

```ts
import { all, desc, op, table } from 'arquero';

// Average hours of sunshine per month, from https://usclimatedata.com/.
const dt = table({
  'Seattle': [69,108,178,207,253,268,312,281,221,142,72,52],
  'Chicago': [135,136,187,215,281,311,318,283,226,193,113,106],
  'San Francisco': [165,182,251,281,314,330,300,272,267,243,189,156]
});

// Sorted differences between Seattle and Chicago.
// Table expressions use arrow function syntax.
dt.derive({
    month: d => op.row_number(),
    diff:  d => d?.Seattle - d?.Chicago
  })
  .select('month', 'diff')
  .orderby(desc('diff'))
  .print();

// Is Seattle more correlated with San Francisco or Chicago?
// Operations accept column name strings outside a function context.
dt.rollup({
    corr_sf:  op.corr('Seattle', 'San Francisco'),
    corr_chi: op.corr('Seattle', 'Chicago')
  })
  .print();

// Aggregate statistics per city, as output objects.
// Reshape (fold) the data to a two column layout: city, sun.
dt.fold(all(), { as: ['city', 'sun'] })
  .groupby('city')
  .rollup({
    min:  d => op.min(d?.sun), // functional form of op.min('sun')
    max:  d => op.max(d?.sun),
    avg:  d => op.average(d?.sun),
    med:  d => op.median(d?.sun),
    // @ts-ignore functional forms permit flexible table expressions
    skew: ({sun: s}) => (op.mean(s) - op.median(s)) / op.stdev(s) || 0
  })
  .objects()
```

gives the error:

```sh
% bun arquero.ts
1 | export default function(message, cause) {
2 |   // @ts-ignore
3 |   throw Error(message, { cause });
            ^
error: Unsupported expression construct: ChainExpression
      at error_default (node_modules/arquero/src/util/error.js:3:9)
      at binary (node_modules/arquero/src/expression/codegen.js:12:16)
      at value (node_modules/arquero/src/expression/parse.js:49:23)
      at parse_default (node_modules/arquero/src/expression/parse.js:72:9)
      at derive (node_modules/arquero/src/verbs/derive.js:18:29)
      at arquero.ts:12:4

Bun v1.1.27 (macOS arm64)
```

Specifically the `dt.derive` call is what is erroring.

**Comment by jheer** [comment]
Thanks for sharing. It looks like you modified the example code to include the `?.` operator. This is not (yet) supported by Arquero's internal parser. It is also not necessary (a `null` or `undefined` datum will not occur) given how Arquero parses and rewrites these functions to process column oriented data. If you're interested in learning more I recommend reading the introductory notebook linked from the README: https://observablehq.com/@uwdata/introducing-arquero

If I remove those edits (for example `d => d?.Seattle - d?.Chicago` -> `d => d.Seattle - d.Chicago`) the example code appears to work as intended.

Hope that helps!

**Comment by bitofbreeze** [comment]
Oh wow sorry about that. I didn't realize the mechanism at hand. FYI typescript indicates `d` can be undefined in those cases and thus prompts this. Is this a shortcoming of typescript support or is there a suggested way of writing this in ts?

**Comment by jheer** [comment]
Thanks for pointing that out! We'll need to look into tightening up the types.
